### PR TITLE
set project version to 2.1

### PR DESCRIPTION
**Pull request by onlyJakob**
set project version to 2.1 in meson_options.txt

### CODE REVIEW

**Comment by artemsen** [comment]
This parameter should be set during the build process. I don't want to change this line on every release =)

**Comment by artemsen** [comment]
Also, this patch breaks the version info because of [this](https://github.com/artemsen/swayimg/blob/2b5cee5ee477e886a2d3189a7e6a2c018f84e084/meson.build#L26).

**Comment by onlyJakob** [comment]
Okay, I didn't see that.

maybe this should be mentioned in the readme, at least in [openSUSE Tumleweed](https://build.opensuse.org/package/show/openSUSE:Factory/swayimg) the version is not set correctly during buildtime. I have submitted a patch there :)

**Comment by artemsen** [comment]
> maybe this should be mentioned in the readme

Maybe. But this is a very specific info just for maintainers.

> in openSUSE Tumleweed the version is not set correctly during buildtime

But this is problem of openSUSE, not a `swayimg` one =)
In [AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=swayimg-git#n7), for example, I set it manually.

**Pull request closed without merging**
